In [2]:
import pandas as pd

In [4]:
pd.Series(['banana',42])

0    banana
1        42
dtype: object

In [7]:
pd.Series(['Wes Mckinney','Creator of pandas'],
          index=['Person','Who'],
         name='data')

Person         Wes Mckinney
Who       Creator of pandas
Name: data, dtype: object

In [10]:
pd.DataFrame({'Name':['Rosaline Franklin','William Gosset'],
             'Occupation':['Chemist','Statistician'],
             'Born':['1920-07-25','1876-06-13'],
             'Died':['1958-04-16','1937-10-16'],
             'Age':[37,61]})

                Name    Occupation        Born        Died  Age
0  Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
1     William Gosset  Statistician  1876-06-13  1937-10-16   61

In [17]:
pd.DataFrame([['Rosaline Franklin','Chemist','1920-07-25','1958-04-16',37],
              ['William Gosset','Statistician','1876-06-13','1937-10-16',61]
             ],
            columns=['Name','Occupation','Born','Died','Age'])

                Name    Occupation        Born        Died  Age
0  Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
1     William Gosset  Statistician  1876-06-13  1937-10-16   61

In [19]:
df = pd.read_csv('data/scientists.csv')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      object
dtypes: int64(1), object(4)
memory usage: 448.0+ bytes

In [24]:
df['Age'].mean()

59.125

In [25]:
df['Age'].var()

335.8392857142857

In [26]:
df['Age'].min()

37

In [27]:
df['Age'].max()

90

In [28]:
df.describe()

             Age
count   8.000000
mean   59.125000
std    18.325918
min    37.000000
25%    44.000000
50%    58.500000
75%    68.750000
max    90.000000

In [29]:
df['Age'][df['Age']>df['Age'].mean()]

1    61
2    90
3    66
7    77
Name: Age, dtype: int64

In [30]:
age = df['Age']
age[age>age.mean()]

1    61
2    90
3    66
7    77
Name: Age, dtype: int64

In [31]:
age>age.mean()

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

In [32]:
age[[True,False,True,True,False,False,False,False]]

0    37
2    90
3    66
Name: Age, dtype: int64

In [33]:
age + 100

0    137
1    161
2    190
3    166
4    156
5    145
6    141
7    177
Name: Age, dtype: int64

In [39]:
age + [100,20,1,1,1,1,1,1]

0    137
1     81
2     91
3     67
4     57
5     46
6     42
7     78
Name: Age, dtype: int64

In [40]:
age + pd.Series([100,20])

0    137.0
1     81.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [41]:
rev_age = age.sort_index()
rev_age

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [42]:
age + rev_age

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [44]:
age.sort_values(ascending=False)

2    90
7    77
3    66
1    61
4    56
5    45
6    41
0    37
Name: Age, dtype: int64

In [45]:
df.loc[[True,False,False,False,True,True,True,False]]

                Name        Born        Died  Age          Occupation
0  Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
4      Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5          John Snow  1813-03-15  1858-06-16   45           Physician
6        Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      object
dtypes: int64(1), object(4)
memory usage: 448.0+ bytes

In [50]:
born = pd.to_datetime(df['Born'],format='%Y-%m-%d')
died = pd.to_datetime(df['Died'],format='%Y-%m-%d')

In [51]:
df['Born_dt'],df['Died_dt'] = born,died

In [55]:
df.head(2)

,Name,Born,Died,Age,Occupation,Born_dt,Died_dt,age_days
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16,13779 days
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16,22404 days

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      object
 5   Born_dt     8 non-null      datetime64[ns]
 6   Died_dt     8 non-null      datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 576.0+ bytes

In [54]:
df['age_days'] = df['Died_dt']-df['Born_dt']
df.head(1)

,Name,Born,Died,Age,Occupation,Born_dt,Died_dt,age_days
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16,13779 days

In [56]:
import random

In [67]:
age = df['Age']
random.seed(42)
random.shuffle(age)

In [70]:
age

0    45
1    56
2    77
3    41
4    37
5    90
6    66
7    61
Name: Age, dtype: int64

In [71]:
df.drop(columns='Born')

,Name,Died,Age,Occupation,Born_dt,Died_dt,age_days
0,Rosaline Franklin,1958-04-16,45,Chemist,1920-07-25,1958-04-16,13779 days
1,William Gosset,1937-10-16,56,Statistician,1876-06-13,1937-10-16,22404 days
2,Florence Nightingale,1910-08-13,77,Nurse,1820-05-12,1910-08-13,32964 days
3,Marie Curie,1934-07-04,41,Chemist,1867-11-07,1934-07-04,24345 days
4,Rachel Carson,1964-04-14,37,Biologist,1907-05-27,1964-04-14,20777 days
5,John Snow,1858-06-16,90,Physician,1813-03-15,1858-06-16,16529 days
6,Alan Turing,1954-06-07,66,Computer Scientist,1912-06-23,1954-06-07,15324 days
7,Johann Gauss,1855-02-23,61,Mathematician,1777-04-30,1855-02-23,28422 days

In [72]:
df.to_pickle('df.pickle')

In [75]:
ddd = pd.read_pickle('df.pickle')

In [76]:
ddd

,Name,Born,Died,Age,Occupation,Born_dt,Died_dt,age_days
0,Rosaline Franklin,1920-07-25,1958-04-16,45,Chemist,1920-07-25,1958-04-16,13779 days
1,William Gosset,1876-06-13,1937-10-16,56,Statistician,1876-06-13,1937-10-16,22404 days
2,Florence Nightingale,1820-05-12,1910-08-13,77,Nurse,1820-05-12,1910-08-13,32964 days
3,Marie Curie,1867-11-07,1934-07-04,41,Chemist,1867-11-07,1934-07-04,24345 days
4,Rachel Carson,1907-05-27,1964-04-14,37,Biologist,1907-05-27,1964-04-14,20777 days
5,John Snow,1813-03-15,1858-06-16,90,Physician,1813-03-15,1858-06-16,16529 days
6,Alan Turing,1912-06-23,1954-06-07,66,Computer Scientist,1912-06-23,1954-06-07,15324 days
7,Johann Gauss,1777-04-30,1855-02-23,61,Mathematician,1777-04-30,1855-02-23,28422 days

In [77]:
df.to_excel('data.xlsx')

In [80]:
import xlwt

In [79]:
!pip install xlwt

Collecting xlwt
  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
     -------------------------------------- 100.0/100.0 kB 5.6 MB/s eta 0:00:00
Installing collected packages: xlwt
Successfully installed xlwt-1.3.0

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [84]:
df.to_excel('data.xls',index=False)

C:\Users\admin\AppData\Local\Temp\ipykernel_13652\2120591488.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  df.to_excel('data.xls',index=False)

In [83]:
pd.read_excel('data.xls',index_col=0)

,Name,Born,Died,Age,Occupation,Born_dt,Died_dt,age_days
0,Rosaline Franklin,1920-07-25,1958-04-16,45,Chemist,1920-07-25,1958-04-16,13779
1,William Gosset,1876-06-13,1937-10-16,56,Statistician,1876-06-13,1937-10-16,22404
2,Florence Nightingale,1820-05-12,1910-08-13,77,Nurse,1820-05-12,1910-08-13,32964
3,Marie Curie,1867-11-07,1934-07-04,41,Chemist,1867-11-07,1934-07-04,24345
4,Rachel Carson,1907-05-27,1964-04-14,37,Biologist,1907-05-27,1964-04-14,20777
5,John Snow,1813-03-15,1858-06-16,90,Physician,1813-03-15,1858-06-16,16529
6,Alan Turing,1912-06-23,1954-06-07,66,Computer Scientist,1912-06-23,1954-06-07,15324
7,Johann Gauss,1777-04-30,1855-02-23,61,Mathematician,1777-04-30,1855-02-23,28422

In [89]:
# import cx_Oracle as co
import oracledb
oracledb.init_oracle_client()

In [91]:
# dsn_tns = co.makedsn('localhost','1521',service_name='xe')
# conn = co.connect('SCOTT/TIGER@localhost:1521/xe')
conn = oracledb.connect('SCOTT/TIGER@localhost:1521/xe')
pd.read_sql('select * from emp',conn)

C:\Users\admin\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

    EMPNO   ENAME        JOB     MGR   HIREDATE     SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0 1980-12-17   800.0     NaN      20
1    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600.0   300.0      30
2    7521    WARD   SALESMAN  7698.0 1981-02-22  1250.0   500.0      30
3    7566   JONES    MANAGER  7839.0 1981-04-02  2975.0     NaN      20
4    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250.0  1400.0      30
5    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850.0     NaN      30
6    7782   CLARK    MANAGER  7839.0 1981-06-09  2450.0     NaN      10
7    7788   SCOTT    ANALYST  7566.0 1987-04-19  3000.0     NaN      20
8    7839    KING  PRESIDENT     NaN 1981-11-17  5000.0     NaN      10
9    7844  TURNER   SALESMAN  7698.0 1981-09-08  1500.0     0.0      30
10   7876   ADAMS      CLERK  7788.0 1987-05-23  1100.0     NaN      20
11   7900   JAMES      CLERK  7698.0 1981-12-03   950.0     NaN      30
12   7902    FORD    ANALYST  7566.0 1981-12-03  3000.0     NaN      20
13   7934  MILLER      CLERK  7782.0 1982-01-23  1300.0     NaN      10