In [10]:
import pandas as pd
import seaborn as sns
import warnings

In [11]:
warnings.filterwarnings('ignore')

In [2]:
tips = sns.load_dataset('tips')

In [3]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
tips['sex_str'] = tips['sex'].astype(str)
# 데이터타입변경 astype

In [5]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
 7   sex_str     244 non-null    object
dtypes: category(4), float64(2), int64(1), object(1)
memory usage: 9.3+ KB

In [8]:
tips['total_bill'].astype(int)

0      16
1      10
2      21
3      23
4      24
       ..
239    29
240    27
241    22
242    17
243    18
Name: total_bill, Length: 244, dtype: int32

In [12]:
tips_sub = tips.head(10)
tips_sub.loc[[1,3,5,7],'total_bill']='missing'
tips_sub

  total_bill   tip     sex smoker  day    time  size sex_str
0      16.99  1.01  Female     No  Sun  Dinner     2  Female
1    missing  1.66    Male     No  Sun  Dinner     3    Male
2      21.01  3.50    Male     No  Sun  Dinner     3    Male
3    missing  3.31    Male     No  Sun  Dinner     2    Male
4      24.59  3.61  Female     No  Sun  Dinner     4  Female
5    missing  4.71    Male     No  Sun  Dinner     4    Male
6       8.77  2.00    Male     No  Sun  Dinner     2    Male
7    missing  3.12    Male     No  Sun  Dinner     4    Male
8      15.04  1.96    Male     No  Sun  Dinner     2    Male
9      14.78  3.23    Male     No  Sun  Dinner     2    Male

In [13]:
tips_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  10 non-null     object
 1   tip         10 non-null     float64
 2   sex         10 non-null     category
 3   smoker      10 non-null     category
 4   day         10 non-null     category
 5   time        10 non-null     category
 6   size        10 non-null     int64
 7   sex_str     10 non-null     object
dtypes: category(4), float64(1), int64(1), object(2)
memory usage: 1.0+ KB

In [14]:
tips_sub['total_bill'].astype(float)

ValueError: could not convert string to float: 'missing'

In [18]:
pd.to_numeric(tips_sub['total_bill'],errors='coerce',downcast='float')

0    16.99
1      NaN
2    21.01
3      NaN
4    24.59
5      NaN
6     8.77
7      NaN
8    15.04
9    14.78
Name: total_bill, dtype: float32

In [22]:
tips['sex'] = tips['sex'].astype('category')

In [23]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
 7   sex_str     244 non-null    object
dtypes: category(4), float64(2), int64(1), object(1)
memory usage: 9.3+ KB

In [24]:
tips['sex'].cat.categories

Index(['Female', 'Male'], dtype='object')

In [25]:
tips['smoker'].cat.categories

Index(['Yes', 'No'], dtype='object')

In [26]:
tips['sex'].cat.codes

0      0
1      1
2      1
3      1
4      0
      ..
239    1
240    0
241    1
242    1
243    0
Length: 244, dtype: int8

In [27]:
cat = ['남자','여자']
tips['sex'].cat.set_categories(cat)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
239    NaN
240    NaN
241    NaN
242    NaN
243    NaN
Name: sex, Length: 244, dtype: category
Categories (2, object): ['남자', '여자']

In [28]:
tips

     total_bill   tip     sex smoker   day    time  size sex_str
0         16.99  1.01  Female     No   Sun  Dinner     2  Female
1         10.34  1.66    Male     No   Sun  Dinner     3    Male
2         21.01  3.50    Male     No   Sun  Dinner     3    Male
3         23.68  3.31    Male     No   Sun  Dinner     2    Male
4         24.59  3.61  Female     No   Sun  Dinner     4  Female
..          ...   ...     ...    ...   ...     ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner     3    Male
240       27.18  2.00  Female    Yes   Sat  Dinner     2  Female
241       22.67  2.00    Male    Yes   Sat  Dinner     2    Male
242       17.82  1.75    Male     No   Sat  Dinner     2    Male
243       18.78  3.00  Female     No  Thur  Dinner     2  Female

[244 rows x 8 columns]