In [178]:
import pandas as pd

In [179]:
df = pd.read_csv('jeju.csv',encoding='cp949')
df.head(2)

,지역,읍면동,전화번호,주소,일반현황,청사현황,자치센터현황,데이터기준일자,Unnamed: 8
0,제주시,일도1동,064-728-4412,제주특별자치도 제주시 중앙로7길 15 (일도일동),인구 3146명 / 면적 0.33㎢ / 11통 61개반,지상 3층 / 연면적 585㎡,개소일 2000-12-20,2019-06-20,NaN
1,제주시,일도2동,064-728-4442,제주특별자치도 제주시 고마로 28 (일도이동),인구 38400명 / 면적2.18㎢ / 48통326반,지상 2층·지하 1층 / 연면적 1307.01,총면적 617.22㎡ / 개소일 2000-12-24,2019-06-20,NaN

In [180]:
#1. 주소 정보를 이용해서 위도, 경도 값을 저장합니다. '위치'컬럼에 (위도,경도) 저장
# 주소를 찾아서 저장하는 함수를 작성하여 처리
# 함수 이름은 geo_coder(query) 리턴값 : (위도,경도) 만일 못찾았다면 '결과없음'으로 리턴
# 데이터프레임적용할때 .apply()사용

In [181]:
def geo_coder(query):
    import requests
    REST_API_KEY = 'ba78bc9aa277131240f5fa32dab22e71'
    query = query.split('(')[0]
    url = f"https://dapi.kakao.com/v2/local/search/keyword.json?category_group_code=PO3&query={query}"
    headers = {'Authorization':f'KakaoAK {REST_API_KEY}'}
    res = requests.get(url,headers=headers)
    jsondata = res.json()
    # print(query)
    # print(jsondata)
    try:
        return jsondata['documents'][0]['y'],jsondata['documents'][0]['x']
    except:
        return '결과없음'

In [182]:
df['위치'] = df['주소'].apply(geo_coder)

In [183]:
df['위치'].head()

0    (33.5150737361162, 126.526342790758)
1                                    결과없음
2    (33.5069402044009, 126.526976882749)
3    (33.4970469392912, 126.535290947586)
4    (33.5041154034239, 126.517362400655)
Name: 위치, dtype: object

In [184]:
df.head(5)

,지역,읍면동,전화번호,주소,일반현황,청사현황,자치센터현황,데이터기준일자,Unnamed: 8,위치
0,제주시,일도1동,064-728-4412,제주특별자치도 제주시 중앙로7길 15 (일도일동),인구 3146명 / 면적 0.33㎢ / 11통 61개반,지상 3층 / 연면적 585㎡,개소일 2000-12-20,2019-06-20,NaN,"(33.5150737361162, 126.526342790758)"
1,제주시,일도2동,064-728-4442,제주특별자치도 제주시 고마로 28 (일도이동),인구 38400명 / 면적2.18㎢ / 48통326반,지상 2층·지하 1층 / 연면적 1307.01,총면적 617.22㎡ / 개소일 2000-12-24,2019-06-20,NaN,결과없음
2,제주시,이도1동,064-728-1530,제주특별자치도 제주시 중앙로25길 17 (이도1동),인구 7418명 / 면적 0.79㎢ / 16통 97개반,지상 2층 / 2층면적 205㎡,개소일 2000-12-28,2019-06-20,NaN,"(33.5069402044009, 126.526976882749)"
3,제주시,이도2동,064-755-2021,제주특별자치도 제주시 오복3길 8 (이도이동),인구 41428명 / 면적 5.4㎢ / 49통 323반,지하 1층·지상 3층 / 연면적 1223.52㎡,총면적 388.9㎡ / 개소일 2000-10-05,2019-06-20,NaN,"(33.4970469392912, 126.535290947586)"
4,제주시,삼도1동,064-728-4532,제주특별자치도 제주시 전농로 40 (삼도일동),인구 14281명 / 면적0.87㎢ / 18통122반,지하 1층·지상3층 / 연면적 2070.37㎡,총면적 456.55㎡,2019-06-20,NaN,"(33.5041154034239, 126.517362400655)"

In [185]:
#2 '위치' 컬럼의 값을 Marker 위치값으로 , tooltip으로 읍면동을 사용하여 지도에 표시(클리스터이용)
# 함수사용, apply()를 이용해 데이터 프레임에 적용

In [186]:
import folium
from folium.plugins import MarkerCluster

In [187]:
def display(loc,map):
    print(loc[0],loc[1])
    if loc[0] != '결과없음':
        folium.Marker(loc[0],tooltip=loc[1]).add_to(map)

In [188]:
map = folium.Map((33.4996213, 126.5311884), zoom_start=8)
map_c = MarkerCluster().add_to(map)
df[['위치','읍면동']].apply(display,map=map_c,axis=1)
map

('33.5150737361162', '126.526342790758') 일도1동
결과없음 일도2동
('33.5069402044009', '126.526976882749') 이도1동
('33.4970469392912', '126.535290947586') 이도2동
('33.5041154034239', '126.517362400655') 삼도1동
('33.5117364099539', '126.522210779319') 삼도2동
('33.50909779859489', '126.51326647018216') 용담1동
('33.5114717601895', '126.511681792482') 용담2동
('33.5150321080548', '126.531518045311') 건입동
('33.52021737989457', '126.5654667308753') 화북동
('33.5218857941584', '126.585599365991') 삼양동
('33.4917232671377', '126.594687244151') 봉개동
('33.4763364526145', '126.545269320539') 아라동
('33.49512911933711', '126.5115798618361') 오라동
('33.4881587279011', '126.496886364509') 연동
('33.4830787815432', '126.477191625104') 노형동
('33.4928558848117', '126.432175190874') 외도동
('33.4997987984561', '126.458099340466') 이호동
('33.5029008833987', '126.468230562279') 도두동
('33.410671262551865', '126.26694451906893') 한림읍
결과없음 애월읍
('33.52252490132381', '126.85205144932898') 구좌읍
('33.53440130090102', '126.63413223748915') 조천읍
('33.3004273889195', '126.183868588586') 한경면
('33.9637161687759', '126.296120635111') 추자면
('33.50645032860738', '126.95298316543516') 우도면
('33.22666983359228', '126.25181131648702') 대정읍
('33.279884789306365', '126.72066566768895') 남원읍
('33.44208942295687', '126.91095279068804') 성산읍
('33.2576271446112', '126.330674173688') 안덕면
('33.3267161051326', '126.830982131689') 표선면
('33.24501690416015', '126.56601476297993') 송산동
('33.24586536852', '126.565248720147') 정방동
결과없음 중앙동
('33.2478169930669', '126.561281643719') 천지동
('33.2633027229827', '126.615561813032') 효돈동
('33.26876038272497', '126.58664440561532') 영천동
('33.2579021227878', '126.568872247568') 동홍동
('33.25596381916347', '126.56017529238014') 서홍동
('33.2481141374087', '126.511357417459') 대륜동
('33.2505202393', '126.477773783616') 대천동
('33.253331287627', '126.43363928392') 중문동
('33.2542812830743', '126.397876776446') 예래동

In [189]:
map = folium.Map((33.4996213, 126.5311884), zoom_start=8)
map_c = MarkerCluster().add_to(map)
for index, row in df.iterrows():
    # print(index)
    # print(row['읍면동'],row['위치'])
    if row['위치'] != '결과없음':
        folium.Marker(row['위치'],tooltip=row['읍면동']).add_to(map_c)
map

In [190]:
#3. '일반현황' 컬럼의 인구수만 분리하여 '인구수'라는 int형 컬럼을 생성

In [191]:
df['인구수'] = df['일반현황'].str.extract('(\d+)').astype(int)
# '일반현황' 컬럼에서 숫자만 추출하여 '인구수'라는 새로운 컬럼을 생성
#  str.extract('(\d+)') '일반현황' 컬럼에서 숫자만 추출하는 정규표현식
df

,지역,읍면동,전화번호,주소,일반현황,청사현황,자치센터현황,데이터기준일자,Unnamed: 8,위치,인구수
0,제주시,일도1동,064-728-4412,제주특별자치도 제주시 중앙로7길 15 (일도일동),인구 3146명 / 면적 0.33㎢ / 11통 61개반,지상 3층 / 연면적 585㎡,개소일 2000-12-20,2019-06-20,NaN,"(33.5150737361162, 126.526342790758)",3146
1,제주시,일도2동,064-728-4442,제주특별자치도 제주시 고마로 28 (일도이동),인구 38400명 / 면적2.18㎢ / 48통326반,지상 2층·지하 1층 / 연면적 1307.01,총면적 617.22㎡ / 개소일 2000-12-24,2019-06-20,NaN,결과없음,38400
2,제주시,이도1동,064-728-1530,제주특별자치도 제주시 중앙로25길 17 (이도1동),인구 7418명 / 면적 0.79㎢ / 16통 97개반,지상 2층 / 2층면적 205㎡,개소일 2000-12-28,2019-06-20,NaN,"(33.5069402044009, 126.526976882749)",7418
3,제주시,이도2동,064-755-2021,제주특별자치도 제주시 오복3길 8 (이도이동),인구 41428명 / 면적 5.4㎢ / 49통 323반,지하 1층·지상 3층 / 연면적 1223.52㎡,총면적 388.9㎡ / 개소일 2000-10-05,2019-06-20,NaN,"(33.4970469392912, 126.535290947586)",41428
4,제주시,삼도1동,064-728-4532,제주특별자치도 제주시 전농로 40 (삼도일동),인구 14281명 / 면적0.87㎢ / 18통122반,지하 1층·지상3층 / 연면적 2070.37㎡,총면적 456.55㎡,2019-06-20,NaN,"(33.5041154034239, 126.517362400655)",14281
5,제주시,삼도2동,064-728-4562,제주특별자치도 제주시 관덕로6길 15 (삼도이동),인구 9431명 / 면적0.83㎢ / 19통109반,지하 1층·지상3층 / 연면적 814㎡,총면적 368.69㎡ / 개소일 2000-12-30,2019-06-20,NaN,"(33.5117364099539, 126.522210779319)",9431
6,제주시,용담1동,064-728-4592,제주특별자치도 제주시 용남3길 11 (용담일동),인구 8368명 / 면적0.61㎢ / 15통102반,지상 3층 / 대지면적 8825㎡ / 건축면적 428.55,연면적 112049㎡ / 개소일 2000-12-24,2019-06-20,NaN,"(33.50909779859489, 126.51326647018216)",8368
7,제주시,용담2동,064-728-1535,제주특별자치도 제주시 흥운길 27 (용담이동),인구 16701명 / 면적 4.94㎢ / 23통 155반,지상 3층 지하 1층 / 연면적 1046.13㎡,총면적 449.55㎡ / 개관일 2000-12-30,2019-06-20,NaN,"(33.5114717601895, 126.511681792482)",16701
8,제주시,건입동,064-728-1536,제주특별자치도 제주시 만덕로 18 (건입동),인구 10850명 / 면적2.5㎢ / 20통113반,지상 4층 / 연면적 1192.37㎡,총면적 323.92㎡ / 개소일 2000-12-27,2019-06-20,NaN,"(33.5150321080548, 126.531518045311)",10850
9,제주시,화북동,064-728-4682,제주특별자치도 제주시 진남로6길 17 (화북일동),인구 25559('17.5월 현재) / 면적8.28㎢ / 33통 205반,지하 1층·지상3층 / 연면적 2375.80㎡,연면적 54㎡ / 개소일 2000-12-27,2019-06-20,NaN,"(33.52021737989457, 126.5654667308753)",25559
10,제주시,삼양동,064-728-1538,제주특별자치도 제주시 지석13길 6 (삼양이동),인구 25000명('19. 1.기준) / 면적 9.525㎢ / 23통 122반,지하 1층·지상 3층 / 연면적 1688.11㎡,총면적 2034㎡ / 개소일 2000-12-28,2019-06-20,NaN,"(33.5218857941584, 126.585599365991)",25000
11,제주시,봉개동,064-728-4742,제주특별자치도 제주시 봉개북1길 15,인구 3046명 / 면적47.2㎢ / 7통30반,지하 1층·지상2층 / 연면적 770㎡,총면적 390㎡ / 개소일 2000-10-05,2019-06-20,NaN,"(33.4917232671377, 126.594687244151)",3046
12,제주시,아라동,064-728-1540,제주특별자치도 제주시 인다8길 5(아라일동),인구 28741명('17.2.28기준) / 면적70.48㎢ / 24통126반,지하 1층·지상3층 / 연면적 453.26㎡,총면적 197.44㎡ / 개소일 2000-12-29,2019-06-20,NaN,"(33.4763364526145, 126.545269320539)",28741
13,제주시,오라동,064-728-1541,제주특별자치도 제주시 오라로 10길 6 (오라2동),인구 13729명 / 면적28.7㎢ / 17통74개반,지하 1층·지상3층 / 연면적815.8㎡,총면적 699.6㎡ / 개소일 2000-12-30,2019-06-20,NaN,"(33.49512911933711, 126.5115798618361)",13729
14,제주시,연동,064-728-4836,제주특별자치도 제주시 신대로 101 (연동),인구 39897 / 면적12.4㎢ / 41통268반,지하 1층·지상3층 / 연면적 945.61㎡,개소일 2001. 9. 5,2019-06-20,NaN,"(33.4881587279011, 126.496886364509)",39897
15,제주시,노형동,064-728-4862,제주특별자치도 제주시 노형9길 9-4 (노형동),인구 56223명('18.12월 말 현재) / 면적 45.24㎢ / 58통 307반,지하 1층·지상3층 / 연면적 733.6㎡,총면적 733.6㎡ / 개소일 2000-12-31,2019-06-20,NaN,"(33.4830787815432, 126.477191625104)",56223
16,제주시,외도동,064-728-4892,제주특별자치도 제주시 일주서로 7350 (외도이동),인구 17606명 / 면적 8.4㎢ / 19통 136반,지상 3층·지하 1층 / 연면적 1847.59㎡,총면적 722.56㎡,2019-06-20,NaN,"(33.4928558848117, 126.432175190874)",17606
17,제주시,이호동,064-728-1545,제주특별자치도 제주시 백포서길 9 (이호일동),인구 4104명 / 면적 2.56㎢ / 8통 37반,지하 1층·지상 2층 / 연면적 543.81㎡,총면적 대지1047㎡ 건축면적 352.84㎡ / 개소일 2001-01-01,2019-06-20,NaN,"(33.4997987984561, 126.458099340466)",4104
18,제주시,도두동,064-728-4952,제주특별자치도 제주시 도두1길 9-1 (도두일동),인구 2837명 / 면적 4.03㎢ / 6통 25반,지상 2층·지하 1층 / 연면적646㎡,총면적 142.41㎡ / 개소일 2000-12-30,2019-06-20,NaN,"(33.5029008833987, 126.468230562279)",2837
19,제주시,한림읍,064-728-7628,제주시 한림읍 한림상로 132,인구 19925명 / 면적91.99㎢ / 21개리 56개자연마을 350개반,지상 2층 / 연면적 1066.33㎡,총면적 1066.33㎡ / 개소일 2007-07-19,2019-06-20,NaN,"(33.410671262551865, 126.26694451906893)",19925
20,제주시,애월읍,064-728-8809,제주특별자치도 제주시 애월읍 하귀로 21길 30,인구 26539명 / 면적202.16㎢ / 26개리70개자연마을317개반,지하 1층·지상2층 / 연면적 618.6㎡,대지면적 1592㎡ / 개소일 2006-03-11,2019-06-20,NaN,결과없음,26539
21,제주시,구좌읍,064-728-7713,제주특별자치도 제주시 구좌읍 일주동로 3116,인구 15080명 / 면적 185.82㎢ / 12개리 60동(자연마을) 220반,지상 2층 / 연면적 1155㎡,총면적 1155㎡ / 개소일 2002-05-22,2019-06-20,NaN,"(33.52252490132381, 126.85205144932898)",15080
22,제주시,조천읍,064-728-7813,제주특별자치도 제주시 조천읍 신북로 194,인구 20804명 / 면적150.64㎢ / 12개리 244개반,지상 2층 / 연면적 1876.38㎡,총면적 555.3㎡ / 개관일 2007-05-10,2019-06-20,NaN,"(33.53440130090102, 126.63413223748915)",20804
23,제주시,한경면,064-728-7913,제주특별자치도 제주시 한경면 칠전로 37,인구 8745명('16.12.31.) / 면적79123㎢ / 15개리 51개자연마을...,지상 2층 / 연면적 602.4㎡,총면적 3369.71㎡ / 개소일 2002-01-08,2019-06-20,NaN,"(33.3004273889195, 126.183868588586)",8745
24,제주시,추자면,064-728-4264,제주특별자치도 제주시 추자면 추자로 26,인구 2820명 / 면적7.05㎢ / 6개리 9개마을 44개반,지하 1층·지상2층 / 연면적 705.46㎡,총면적 364.3㎡ / 개소일 2006-03-16,2019-06-20,NaN,"(33.9637161687759, 126.296120635111)",2820
25,제주시,우도면,064-728-1527,제주특별자치도 제주시 우도면 우도로 153,인구 1718명 / 면적 6.07㎢ / 4개리 12개자연마을 20개반,지상 2층 / 연면적 402㎡,총면적 402㎡ / 개소일 : 2006-08-25,2019-06-20,NaN,"(33.50645032860738, 126.95298316543516)",1718
26,서귀포시,대정읍,064-760-4012,제주특별자치도 서귀포시 대정읍 하모중앙로 20,인구 16610명 / 면적 78.53㎢ / 23개리 240개반,지상 2층·지하 1층 / 연면적 986.95㎡(본관),총면적 149㎡ / 개소일 2006-08-29,2019-06-20,NaN,"(33.22666983359228, 126.25181131648702)",16610
27,서귀포시,남원읍,064-760-4118,제주특별자치도 서귀포시 남원읍 태위로 695,인구 19151명 / 면적 188.70㎢ / 17개리 187개반('16.12.31 기준),지상 3층·지하 1층 / 연면적 1044.02㎡,총면적 486m² / 개소일 2000-10-26,2019-06-20,NaN,"(33.279884789306365, 126.72066566768895)",19151
28,서귀포시,성산읍,064-760-4214,제주특별자치도 서귀포시 성산읍 일주동로 4330,인구 13866명 / 면적 107.673㎢ / 14개리 152개반,지하 1층·지상 2층 / 연면적 1272.22㎡,총면적 347.15㎡ 중 275.42㎡,2019-06-20,NaN,"(33.44208942295687, 126.91095279068804)",13866
29,서귀포시,안덕면,064-760-4320,제주특별자치도 서귀포시 안덕면 화순서서로 74,인구 11867명 ('18.12.31.기준) / 면적 105.58㎢ / 12개리 1...,지상 2층,총면적 155㎡ / 개소일 2000-11-14,2019-06-20,NaN,"(33.2576271446112, 126.330674173688)",11867
30,서귀포시,표선면,064-760-4413,제주특별자치도 서귀포시 표선면 표선중앙로 74,인구 11167명 / 면적 135.172㎢ / 10개리 94개반,지상 2 층 지하 1층,총면적 214㎡ / 개소일 2006-08-16,2019-06-20,NaN,"(33.3267161051326, 126.830982131689)",11167
31,서귀포시,송산동,064-760-4503,제주특별자치도 서귀포시 소암로 4 (서귀동),인구 5207명 / 면적 4.8㎢ / 2통 11반,지상 3층 지하 1층 / 연면적 1077㎡,총면적 276.6㎡ / 개소일 2000-12-28,2019-06-20,NaN,"(33.24501690416015, 126.56601476297993)",5207
32,서귀포시,정방동,064-760-4541,제주특별자치도 서귀포시 태평로421번길 7,인구 2444명,지상 3층 지하 1층 / 연면적 769.87㎡,NaN,2019-06-20,NaN,"(33.24586536852, 126.565248720147)",2444
33,서귀포시,중앙동,064-760-4562,제주특별자치도 서귀포시 동문동로 27 (서귀동),인구 4003명('17. 12. 31. 현재) 면적 0.45㎢ 8통 41반,지상 3층 지하 1층 (연면적 769.87㎡),NaN,2019-06-20,NaN,결과없음,4003
34,서귀포시,천지동,064-760-4593,제주특별자치도 서귀포시 중정로47번길 3 (서귀동),인구 3798명 / 면적 1.39㎢ / 6통 30반,지상 2층 지하 1층 / 연면적646㎡,총면적 53평 / 개소일 2001-01-05,2019-06-20,NaN,"(33.2478169930669, 126.561281643719)",3798
35,서귀포시,효돈동,064-767-1535,제주특별자치도 서귀포시 남선동산로 26 (하효동),인구 5475명 / 면적 6.6㎢ / 2통 9반,지상 3층 지하 1층,총면적 147평 / 개소일 2000-12-29,2019-06-20,NaN,"(33.2633027229827, 126.615561813032)",5475
36,서귀포시,영천동,064-760-4664,제주특별자치도 서귀포시 토평로 15 (토평동),2082 가구 4980명 / 면적 46.33㎢ / 5통 36반('12.12.31 현재),지상 2층 지하 1층,총면적 136.5㎡ / 개소일 2001-01-04,2019-06-20,NaN,"(33.26876038272497, 126.58664440561532)",2082
37,서귀포시,동홍동,064-760-4682,제주특별자치도 서귀포시 동홍로 104 (동홍동),인구 22225명 / 면적 14.3㎢ / 11통 124반,지상 2층 지하 1층 / 연면적 1934.31㎡,개소일 2001-01-04,2019-06-20,NaN,"(33.2579021227878, 126.568872247568)",22225
38,서귀포시,서홍동,064-760-4745,제주특별자치도 서귀포시 중앙로 125(서홍동),인구 10697명('18.12.31. 현재) / 면적 13.34k㎡ / 5통 30반,지상 3층 / 연면적 1134㎡,총면적 631.47㎡ / 개소일 2000-12-27,2019-06-20,NaN,"(33.25596381916347, 126.56017529238014)",10697
39,서귀포시,대륜동,064-760-4755,제주특별자치도 서귀포시 일주동로 9185 (법환동),인구 10344명('15.05.31일현재) / 면적 22.24㎢ / 4통 17반,지상 3층 / 연면적 914.28㎡(부지면적 2029㎡),총면적 526㎡ / 개소일 2001-01-05,2019-06-20,NaN,"(33.2481141374087, 126.511357417459)",10344
40,서귀포시,대천동,064-760-4785,제주특별자치도 서귀포시 도순로 44 (도순동),인구 11310명 / 면적 50.5㎢ / 7통 51반 ('17.4.30기준),지상 2층 / 연면적 300.48㎡,총면적 90평 / 개소일 2000-12-28,2019-06-20,NaN,"(33.2505202393, 126.477773783616)",11310
41,서귀포시,중문동,064-760-4818,제주특별자치도 서귀포시 1100로 30 (중문동),인구 10684명 / 면적 56.44㎢ / 4통 49반,지상 3층 / 연면적 2407.5㎡,총면적 2407.5㎡ / 개소일 2000-11-02,2019-06-20,NaN,"(33.253331287627, 126.43363928392)",10684
42,서귀포시,예래동,064-760-4864,제주특별자치도 서귀포시 예래로 82 (상예동),인구 3813명 / 면적 37.7㎢ / 5통 30반,지상 2층·지하 1층 / 연면적 449.14㎡,총면적 47평 / 개소일 2000-12-27,2019-06-20,NaN,"(33.2542812830743, 126.397876776446)",3813

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   지역          43 non-null     object
 1   읍면동         43 non-null     object
 2   전화번호        43 non-null     object
 3   주소          43 non-null     object
 4   일반현황        43 non-null     object
 5   청사현황        43 non-null     object
 6   자치센터현황      41 non-null     object
 7   데이터기준일자     43 non-null     object
 8   Unnamed: 8  0 non-null      float64
 9   위치          43 non-null     object
 10  인구수         43 non-null     int32
dtypes: float64(1), int32(1), object(9)
memory usage: 3.7+ KB

In [193]:
df['일반현황'].str.split('/').str.get(0).str.split('(').str.get(0).str.split().str.get(-1).str.replace('명','').astype(int)

0      3146
1     38400
2      7418
3     41428
4     14281
5      9431
6      8368
7     16701
8     10850
9     25559
10    25000
11     3046
12    28741
13    13729
14    39897
15    56223
16    17606
17     4104
18     2837
19    19925
20    26539
21    15080
22    20804
23     8745
24     2820
25     1718
26    16610
27    19151
28    13866
29    11867
30    11167
31     5207
32     2444
33     4003
34     3798
35     5475
36     4980
37    22225
38    10697
39    10344
40    11310
41    10684
42     3813
Name: 일반현황, dtype: int32

In [198]:
import re
# df['인구수'] = df['일반현황'].apply(lambda x:int(re.findall('[0-9]{4,}',x)[-1]))
df['일반현황'].apply(lambda x:int(re.findall('[0-9]{4,}',x)[-1]))

0      3146
1     38400
2      7418
3     41428
4     14281
5      9431
6      8368
7     16701
8     10850
9     25559
10    25000
11     3046
12    28741
13    13729
14    39897
15    56223
16    17606
17     4104
18     2837
19    19925
20    26539
21    15080
22    20804
23    79123
24     2820
25     1718
26    16610
27    19151
28    13866
29    11867
30    11167
31     5207
32     2444
33     4003
34     3798
35     5475
36     4980
37    22225
38    10697
39    10344
40    11310
41    10684
42     3813
Name: 일반현황, dtype: int64

In [199]:
df.head(2)

,지역,읍면동,전화번호,주소,일반현황,청사현황,자치센터현황,데이터기준일자,Unnamed: 8,위치,인구수
0,제주시,일도1동,064-728-4412,제주특별자치도 제주시 중앙로7길 15 (일도일동),인구 3146명 / 면적 0.33㎢ / 11통 61개반,지상 3층 / 연면적 585㎡,개소일 2000-12-20,2019-06-20,NaN,"(33.5150737361162, 126.526342790758)",3146
1,제주시,일도2동,064-728-4442,제주특별자치도 제주시 고마로 28 (일도이동),인구 38400명 / 면적2.18㎢ / 48통326반,지상 2층·지하 1층 / 연면적 1307.01,총면적 617.22㎡ / 개소일 2000-12-24,2019-06-20,NaN,결과없음,38400